/* Generated By:JJTree: Do not edit this line. OStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=O,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.orientechnologies.orient.core.sql.parser;

import com.orientechnologies.common.exception.OException;
import com.orientechnologies.orient.core.command.OBasicCommandContext;
import com.orientechnologies.orient.core.command.OCommandContext;
import com.orientechnologies.orient.core.db.ODatabaseDocumentInternal;
import com.orientechnologies.orient.core.db.ODatabaseSession;
import com.orientechnologies.orient.core.exception.OCommandExecutionException;
import com.orientechnologies.orient.core.sql.OCommandSQLParsingException;
import com.orientechnologies.orient.core.sql.executor.OExecutionPlan;
import com.orientechnologies.orient.core.sql.executor.OInternalExecutionPlan;
import com.orientechnologies.orient.core.sql.executor.OResult;
import com.orientechnologies.orient.core.sql.executor.OResultInternal;
import com.orientechnologies.orient.core.sql.executor.OResultSet;
import com.orientechnologies.orient.core.sql.executor.resultset.OExecutionResultSet;
import com.orientechnologies.orient.core.sql.executor.resultset.OExecutionStream;
import java.util.Map;

public class OStatement extends SimpleNode {

  // only for internal use!!! (caching and profiling)
  protected String originalStatement;

  public static final String CUSTOM_STRICT_SQL = "strictSql";

  public OStatement(int id) {
    super(id);
  }

  public OStatement(OrientSql p, int id) {
    super(p, id);
  }

  public void toString(Map<Object, Object> params, StringBuilder builder) {
    builder.append(originalStatement);
  }

  @Override
  public void toGenericStatement(StringBuilder builder) {
    builder.append(originalStatement);
  }

  public void validate() throws OCommandSQLParsingException {}

  @Override
  public String toString(String prefix) {
    StringBuilder builder = new StringBuilder();
    toString(null, builder);
    return builder.toString();
  }

  public OResultSet execute(ODatabaseSession db, Object[] args, boolean usePlanCache) {
    return execute(db, args, null, usePlanCache);
  }

  public OResultSet execute(ODatabaseSession db, Map args, boolean usePlanCache) {
    return execute(db, args, null, usePlanCache);
  }

  public OResultSet execute(
      ODatabaseSession db, Object[] args, OCommandContext parentCtx, boolean usePlanCache) {
    OBasicCommandContext ctx = new OBasicCommandContext(db);
    if (parentCtx != null) {
      ctx.setParentWithoutOverridingChild(parentCtx);
    }
    ctx.setArrayParameters(args);
    OInternalExecutionPlan executionPlan = resolvePlan(usePlanCache, ctx);
    return new OLocalResultSet(executionPlan, ctx);
  }

  public static OResultSet executeAll(OCommandContext ctx, OInternalExecutionPlan plan) {
    return new OExecutionResultSet(OExecutionStream.collectAll(plan.start(ctx), ctx), ctx, plan);
  }

  public OInternalExecutionPlan resolvePlan(boolean useCache, OCommandContext ctx) {
    if (useCache && !ctx.isProfiling() && executinPlanCanBeCached()) {
      OExecutionPlan plan =
          OExecutionPlanCache.get(
              getOriginalStatement(), ctx, (ODatabaseDocumentInternal) ctx.getDatabase());
      if (plan != null) {
        return (OInternalExecutionPlan) plan;
      }
    }
    return createExecutionPlan(ctx);
  }

  public OResultSet execute(
      ODatabaseSession db, Map params, OCommandContext parentCtx, boolean usePlanCache) {
    OBasicCommandContext ctx = new OBasicCommandContext(db);
    if (parentCtx != null) {
      ctx.setParentWithoutOverridingChild(parentCtx);
    }
    ctx.setInputParameters(params);

    OInternalExecutionPlan executionPlan = resolvePlan(usePlanCache, ctx);

    return new OLocalResultSet(executionPlan, ctx);
  }

  /**
   * creates an execution plan for current statement, with profiling disabled
   *
   * @param ctx the context that will be used to execute the statement
   * @return an execution plan
   */
  public OInternalExecutionPlan createExecutionPlan(OCommandContext ctx) {
    return createExecutionPlan(ctx);
  }

  public OInternalExecutionPlan createExecutionPlanNoCache(OCommandContext ctx) {
    return createExecutionPlan(ctx);
  }

  public OStatement copy() {
    throw new UnsupportedOperationException("IMPLEMENT copy() ON " + getClass().getSimpleName());
  }

  public boolean refersToParent() {
    throw new UnsupportedOperationException(
        "Implement " + getClass().getSimpleName() + ".refersToParent()");
  }

  public boolean isIdempotent() {
    return false;
  }

  public static OStatement deserializeFromOResult(OResult doc) {
    try {
      OStatement result =
          (OStatement)
              Class.forName(doc.getProperty("__class"))
                  .getConstructor(Integer.class)
                  .newInstance(-1);
      result.deserialize(doc);
    } catch (Exception e) {
      throw OException.wrapException(new OCommandExecutionException(""), e);
    }
    return null;
  }

  public OResult serialize() {
    OResultInternal result = new OResultInternal();
    result.setProperty("__class", getClass().getName());
    return result;
  }

  public void deserialize(OResult fromResult) {
    throw new UnsupportedOperationException();
  }

  public boolean executinPlanCanBeCached() {
    return false;
  }

  public String getOriginalStatement() {
    return originalStatement;
  }

  public void setOriginalStatement(String originalStatement) {
    this.originalStatement = originalStatement;
  }
}
/* JavaCC - OriginalChecksum=589c4dcc8287f430e46d8eb12b0412c5 (do not edit this line) */
